# This is a basic workflow to help you get started with Actions

name: Membrane-Hub CI

# Controls when the action will run. 
on: [push]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd membrane-viewer-js && npm install
    - run: cd membrane-viewer-js && npm run build --if-present
    - run: pm2 reload ./membrane-viewer-js/run.sh
      env:
        CI: true
